### ISSUE TITLE
Trello Alerts is Killing hubot-slack

### ISSUE THREAD

**Issue by rowi1de** [slackapi/hubot-slack#403] opened 2017-03-17 11:15 UTC
* [X ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [ X] I've read and agree to the [Code of Conduct](https://github.com/slackapi/hubot-slack/blob/master/CODE_OF_CONDUCT.md).
* [ X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
Trello Alerts is Killing hubot-slack

#### Reproducible in:
"hubot": "2.19.0", "hubot-slack": "4.3.3",

#### Steps to reproduce:

1.  Add https://slack.com/apps/A0F814C4R-trello-alerts Trello Alerts to a channel
2. Configure "New Checklist" Alert
3.  Add Hubot
4. Add a Checklist on your trello board

### Expected result:
Hubot doesn't care

### Actual result:
 Hubot Crashed

### Attachments:
```
Mar 17 09:01:33 xxx-bot app/web.1:  [Fri Mar 17 2017 09:01:32 GMT+0100 (CET)] INFO Logged in as xxx-bot of XXX
Mar 17 09:01:33 xxx-bot app/web.1:  [Fri Mar 17 2017 09:01:32 GMT+0100 (CET)] INFO Slack client now connected 
Mar 17 09:01:33 xxx-bot app/web.1:  [Fri Mar 17 2017 09:01:32 GMT+0100 (CET)] DEBUG Received message: 'New checklist "Voraussetzungen (https://trello.com/c/uvMzQLmR)" added to card "SAFe Speaker @ ScrumDay 2018 (https://trello.com/c/uvMzQLmR)"' in channel: safe, from: Trello 
Mar 17 09:01:33 xxx-bot app/web.1:  [Fri Mar 17 2017 09:01:32 GMT+0100 (CET)] DEBUG No listeners executed; falling back to catch-all 
Mar 17 09:01:33 xxx-bot app/web.1:  [Fri Mar 17 2017 09:01:32 GMT+0100 (CET)] ERROR TypeError: Cannot call method 'toString' of undefined 
Mar 17 09:01:33 xxx-bot app/web.1:    at new User (/app/node_modules/hubot/src/user.coffee:9:19, <js>:14:47) 
Mar 17 09:01:33 xxx-bot app/web.1:    at Brain.userForId (/app/node_modules/hubot/src/brain.coffee:106:7, <js>:93:16) 
Mar 17 09:01:33 xxx-bot app/web.1:    at SlackBot.userChange (/app/node_modules/hubot-slack/src/bot.coffee:233:5, <js>:307:31) 
Mar 17 09:01:33 xxx-bot app/web.1:    at RTMClient.<anonymous> (/app/node_modules/hubot-slack/src/bot.coffee:1:1, <js>:3:61) 
Mar 17 09:01:33 xxx-bot app/web.1:    at RTMClient.emit (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/eventemitter3/index.js:116:35) 
Mar 17 09:01:33 xxx-bot app/web.1:    at RTMClient.emit (/app/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/client.js:79:39) 
Mar 17 09:01:33 xxx-bot app/web.1:    at RTMClient._handleWsMessageViaEventHandler (/app/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/rtm/client.js:465:10) 
Mar 17 09:01:33 xxx-bot app/web.1:    at RTMClient.handleWsMessage (/app/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/rtm/client.js:419:10) 
Mar 17 09:01:33 xxx-bot app/web.1:    at WebSocket.wrapper (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:4968:19) 
Mar 17 09:01:33 xxx-bot app/web.1:    at WebSocket.emit (events.js:98:17) 
Mar 17 09:01:33 xxx-bot app/web.1:    at Receiver.ontext (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/ws/lib/WebSocket.js:841:10) 
Mar 17 09:01:33 xxx-bot app/web.1:    at /app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:536:18 
Mar 17 09:01:33 xxx-bot app/web.1:    at Receiver.applyExtensions (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:371:5) 
Mar 17 09:01:33 xxx-bot app/web.1:    at /app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:508:14 
Mar 17 09:01:33 xxx-bot app/web.1:    at Receiver.flush (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:347:3) 
Mar 17 09:01:33 xxx-bot app/web.1:    at Receiver.opcodes.1.finish (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:541:12) 
Mar 17 09:01:33 xxx-bot app/web.1:    at Receiver.expectHandler (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:499:31) 
Mar 17 09:01:33 xxx-bot app/web.1:    at Receiver.add (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:103:24) 
Mar 17 09:01:33 xxx-bot app/web.1:    at CleartextStream.realHandler (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/ws/lib/WebSocket.js:825:20) 
Mar 17 09:01:33 xxx-bot app/web.1:    at CleartextStream.emit (events.js:95:17) 
Mar 17 09:01:33 xxx-bot app/web.1:    at CleartextStream.<anonymous> (_stream_readable.js:765:14) 
Mar 17 09:01:33 xxx-bot app/web.1:    at CleartextStream.emit (events.js:92:17) 
Mar 17 09:01:33 xxx-bot app/web.1:    at emitReadable_ (_stream_readable.js:427:10) 
Mar 17 09:01:33 xxx-bot app/web.1:    at _stream_readable.js:420:7 
Mar 17 09:01:33 xxx-bot app/web.1:    at process._tickCallback (node.js:458:13) 
```

**Comment by aoberoi** [comment] 2017-10-19 04:41
i think this _might_ be a duplicate of #391, which has been fixed. is this issue still occurring for you?

**Comment by aoberoi** [comment] 2017-10-19 04:41
@ rowi1de ping!

**Comment by aoberoi** [comment] 2017-10-19 04:42
@rowi1de i think this _might_ be a duplicate of #391, which has been fixed. is this issue still occurring for you?

**Comment by rowi1de** [comment] 2017-10-19 06:54
I don’t have this test setup anymore, so can’t reproduce or test the fix. But the stacktrace looks very similar

**Comment by aoberoi** [comment] 2017-10-19 17:54
Thanks for the update @rowi1de. 

Closing this issue for now then. If it does pop back up, feel free to comment.

**Closed by aoberoi** 2017-10-19 17:54 UTC
Labels: needs feedback
