### ISSUE TITLE
An error occurs when IFTTT processes a message linked to slack

### ISSUE THREAD

**Issue by mininobu** [slackapi/hubot-slack#500] opened 2018-06-24 09:13 UTC
### Description
I am trying to operate RM Mini 3 using Google Home (Google Assistant), IFTTT, Slack, hubot-broadlink-rm.
When talking to Google Home, it is transmitted to IFTTT, IFTTT sends a message to Slack, and hubot - broadlink - rm operates RM Mini 3.
※Ref: https://scrapbox.io/smart-home/10%E3%83%89%E3%83%AB%E3%81%AERM_Mini3%E3%81%A8Google_Home%E3%81%A7%E5%AE%B6%E9%9B%BB%E3%82%92%E6%93%8D%E4%BD%9C%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95

If you send a message from slack app to slack's hubot it will succeed, but sending a message from IFTTT to slack-hubot will result in an error "ERROR An error occurred while processing. RTM event: a is not defined." .

I succeeded when I tried it before (January 2018), but when I made a new environment to Raspberry Pi on June 19, I began to fail.
Please advise if you know its cause, solution.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version:4.5.1

node version:v8.11.3

OS version(s):Raspbian 9.1（Raspberry Pi 3）

#### Steps to reproduce:

1. execute hubot bin/hubot --adapter slack
2. wait for hubot to connect to Slack RTM
3. Send a message from IFTTT
　　IFTTT "that" info
          Which channel? => Direct Message / @homebot
          Message             => send tv:on
     ※The message was sent from the Android application of IFTTT.
4. A message arrives from IFTTT to Slack (it is confirmed that it will be displayed by the Slack application)
5. An error occurs in hubot / bin on Raspberry Pi.

#### Expected result:
There should be no error in hubot / bin on Raspberry Pi.
RM Mini to operate.

#### Actual result:
Slack RTM Error
ERROR An error occurred while processing an RTM event: a is not defined.

#### Attachments:
```
bin/hubot --adapter slack
npm WARN hubot-help@0.2.2 requires a peer of coffee-script@^1.12.6 but none is installed. You must install peer dependencies yourself.

audited 391 packages in 9.825s
[Sun Jun 24 2018 08:21:15 GMT+0000 (UTC)] INFO hubot-slack adapter v4.5.1
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
[Sun Jun 24 2018 08:21:16 GMT+0000 (UTC)] INFO Logged in as @homebot in workspace home
[Sun Jun 24 2018 08:21:16 GMT+0000 (UTC)] INFO Connected to Slack RTM
[Sun Jun 24 2018 08:21:18 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Sun Jun 24 2018 08:21:18 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
Discovered Broadlink RM device at xxx.xxx.xxx.xxx (xx:xx:xx:xx:xx:xx)

[Sun Jun 24 2018 08:21:48 GMT+0000 (UTC)] ERROR An error occurred while processing an RTM event: a is not defined.
```

**Comment by mininobu** [comment] 2018-06-24 17:28
Additional Information.
After executing with the setting to display the debug log, the following log is displayed.
※Channel is masking.

```
[Sun Jun 24 2018 17:14:17 GMT+0000 (UTC)] DEBUG Received text message in channel: XXXXXXXXX, from: undefined (bot)
[Sun Jun 24 2018 17:14:17 GMT+0000 (UTC)] ERROR An error occurred while processing an RTM event: a is not defined.
```

I think that "from: undefined (bot)" is the cause, but I do not know the reason.

**Comment by aoberoi** [comment] 2018-06-25 01:57
@mininobu thanks for the detailed bug report, its very helpful!

i think the fact that the user.id is `undefined` is actually okay. this is expected when a bot message that was sent as a custom integration or an app without a bot user. i suspect that is how IFTTT is interacting with Slack.

i looked a little closer at the code, and this line seems potentially related: https://github.com/slackapi/hubot-slack/blob/2d3a229a4d9e3b61b1480cf7fc68e659d6d6e76a/src/message.coffee#L94

this is the only place where i see a variable named `a`. the strange part is that i don't see how it could be undefined. if `attachments` exists, and `.map()` is called on it, by definition there needs to be an element.

sorry i don't have a solution yet, but i'll keep digging. my next step is to try and reproduce the issue.

**Comment by aoberoi** [comment] 2018-06-25 02:00
oh, it looks like that line is the problem! i used the coffeescript website to transpile the single line to see what the javascript output is, out of curiosity. here it is: https://coffeescript.org/v1/#try:rawMessage.attachments.map(a%20-%3E%20a.fallback).join(%22%5Cn%22)%20

notice that it treats `a` as a function! that's not right. labeling this as a bug, and it should be pretty easy to fix.

**Comment by aoberoi** [comment] 2018-06-25 06:04
@mininobu we haven't merged and released yet, but i hope to do so by the end of the week.

if this is an emergency for you or your team, i can try to prioritize this ahead of some other tasks, but right now i'd like to hold off on making a release until we can get to the bottom of #379 and one more issue.

i don't recommend updating your own `message.coffee` with the patch, but if you need this to work right away, that is probably your best option. i advise that you update to 4.5.2 as soon as its available.

**Comment by mininobu** [comment] 2018-06-25 15:30
@aoberoi 
I understand.
We are waiting for 4.5.2 to be released.
Thank you.

**Closed** 2018-07-03 23:59 UTC
Labels: bug

**Comment by aoberoi** [comment] 2018-07-04 00:31
@mininobu 4.5.2 has been published! thanks for your patience.

**Comment by mininobu** [comment] 2018-07-05 13:08
@aoberoi Thank you for contacting. I tried immediately.
From the conclusion it was useless.
The error log is not displayed, but "from: undefined (bot)" is output and hubot - broadlink - rm does not respond.
```
DEBUG Received text message in channel: XXXXXXXXX, from: undefined (bot)
DEBUG No listeners executed; falling back to catch-all
```

Sending a message from the slack application will succeed. At that time, the following log will appear.
```
DEBUG Received text message in channel: D8P3880TD, from: U8NB4JN5N (human)
```
Have you noticed the cause?

**Comment by aoberoi** [comment] 2018-07-05 18:31
@mininobu i'm sorry, it seems this change only partially fixed the issue. it looks like there's more problems still. let's create a new issue so that we can treat these as two separate topics. i've created #504 for that purpose.
