### ISSUE TITLE
Cant run hubot-slack via. script

### ISSUE THREAD

**Issue by Ewan-Walker** [slackapi/hubot-slack#283] opened 2016-03-06 22:06 UTC
I have a bash script that i was testing with to house all the environment variables however - it seems I cannot start it via. a script

```
'- Error: Cannot find module 'hubot-slack ERROR Cannot load adapter slack
```

However if I start it directly via command line - It works fine:

```
PORT=3000 HUBOT_SLACK_TOKEN=MY_TOKEN ./bin/hubot -a slack
```

the script is just a bash script with the same line as above in it, is there something I am missing?

**Comment by DEGoodmanWilson** [comment] 2016-06-27 19:02
I'm sorry to say that this sounds like an issue with your local environment :( I'm going to close this issue for now.

**Comment by ridderholt** [comment] 2017-01-19 20:02
I got the same issue today, the only thing I did with Hubot was upgrading the slack adapter to version 4.3.1 and when I redeployed Hubot (hosted as a Node site in Azure) it wouldn't start and in the logs I got:
```ERROR Cannot load adapter slack - Error: Cannot find module 'hubot'```

It works fine when I run it locally (tried both on a Ubuntu 16.10 machine and a Win 10 machine). I finally gave up and downgrade to version 3.4.2 of the slack adapter and now it works in Azure again.

Please let me know if you require any further info!

**Comment by Templier** [comment] 2017-01-24 06:10
I was able to fix it by replacing the two instances of ``require.main.require`` by simply ``require``.

The reason it works locally but not when hosted on Azure may be related to the fact that it is likely run via a direct call to node locally while it's hosted in IIS when running on Azure.

**Comment by crahrig** [comment] 2017-08-15 06:33
@ridderholt did you ever end up figuring out how to get the version 4.X.X of the slack adapter working?

@Templier did you make those changes in your server.js file? Or are you referring to another file? Because that still did not solve the problem for me. I was only able to get it working by downgrading.

**Comment by aoberoi** [comment] 2017-08-15 16:37
@crahrig are you also trying to host your hubot program on Azure? If so, and if you can point me towards a guide on getting a similar setup on Azure, I will try to reproduce the issue and help solve it.

**Comment by crahrig** [comment] 2017-08-15 16:47
Sure @aoberoi, I used three main sources to get everything deployed:
1. [How to deploy Hubot in Slack to an Azure Website](http://jasonpoon.ca/2015/06/12/how-to-deploy-hubot-in-slack-to-azure/)
2. [Hubot Documentation - Deploying to Azure](https://hubot.github.com/docs/deploying/azure)
3. [Running Hubot in an Azure Website](https://cultureops.wordpress.com/2015/06/03/running-hubot-in-an-azure-website/)

As I mentioned in my last comment I was only able to get it working on Azure once I downgraded my Slack adapter within my Hubot as @Templier suggested. My deployed code is found here: https://github.com/crahrig/flamebot

**Comment by crahrig** [comment] 2017-08-31 15:23
@aoberoi any update on this particular issue?

**Comment by crahrig** [comment] 2017-11-23 05:44
@aoberoi checking in once more to see if anything came of you trying to repo the issue?

**Comment by aoberoi** [comment] 2017-12-18 05:08
@crahrig sorry, this totally slipped off my radar. most likely because it was marked closed. i'm opening it now and i hope to return to it soon.

**Comment by aoberoi** [comment] 2018-01-22 11:05
I think I now understand the problem. The instructions all mention creating a new file called `server.js` which contains the following code:

```
require(‘coffee-script/register’);
module.exports = require(‘hubot/bin/hubot.coffee’);
```

In order to load the `hubot` code, we employ a trick of using `require.main.require('hubot')` in order to get around the trade-offs mentioned in #137. we expect `require.main` to be a reference to the module that requires the `hubot` package directly in its package `dependencies`. But, those instructions have you inject that `server.js` program as the entry point, and therefore our assumption isn't true anymore.

I'm thinking about how exactly we should support this. #138 might be a plausible solution. i'm open to other thoughts.

**Comment by aoberoi** [comment] 2018-01-23 23:56
*Update:* I was able to reproduce the issue on my own test instance in Azure.

I think the best way forward is to invest in providing updated Azure deployment instructions, and possibly seeding these instructions up to the hubotio/hubot as a contribution to that project's docs. I'm not 100% certain that updated instructions will alone fix this issue, but I know that's at least one problem, since Azure has already deprecated the CLI product and no longer has an offering called Azure Websites (its now known as Azure Web Apps, part of Azure App Service). I'm even thinking we might want to build an ARM (Azure Resource Manager) template to get as close to a one-click deploy as possible. Microsoft hosts a directory for these templates to be shared publicly, and the following documentation describes the experience we could enable: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy-portal#deploy-resources-from-marketplace.

I'm going to close this ticket in favor of a brand new one that more accurately describes the Azure-related work.

**Closed by aoberoi** 2018-01-23 23:56 UTC
Labels: bug
