### ISSUE TITLE
V3 regression: missing msg.message.user.reply_to 

### ISSUE THREAD

**Issue by idan** [slackapi/hubot-slack#150] opened 2015-02-03 13:07 UTC
We're working on making our chatops slack-compatible, and we discovered that almost everything broke because we're missing the `reply_to` room id on messages. It seems like it all got nuked in c14b4d1.

Maybe we're the ones missing something in relying on it?

**Comment by ys** [comment] 2015-02-03 13:10
We were on hipchat and plan to make it compatible.
I know that hipchat relies on this. Maybe this is a smell we have.
Could you point us in the right direction if you think it is not a regression

**Comment by evansolomon** [comment] 2015-02-03 19:38
I doubt it was removed intentionally, and I doubt you're doing anything wrong by using it.  This does seem to be an often difficult problem between different Hubot adapters where data that seem "standard" in one are inexplicably missing in another.  Might be cool if there was some kind of standardization either in what's there or how to communicate what's going to be there.

Anyway, this seems like a legit bug I think.

**Comment by paulhammond** [comment] 2015-02-09 21:22
Just confirming this wasn't a deliberate regression. Not sure when I'm going to get to work on fixing it, but we'll definitely accept a pull request!

**Comment by DEGoodmanWilson** [comment] 2016-08-05 14:32
Working on this regression now, y'all. I might have a fix ready, but I wonder y'all could help me? Can you show me an example script I could run that demonstrates the broken behavior, to help me write some unit tests around this bug?

**Comment by johnagan** [comment] 2017-01-10 18:34
Is this still a bug?

**Comment by aoberoi** [comment] 2017-10-17 15:39
@idan @ys @evansolomon i know it has been a very long time since this issue was opened, but i'd still like to address this!

can someone provide a script that utilized this `msg.message.user.reply_to` property so i can understand how its meant to behave? unfortunately, i haven't been involved in the project long enough to understand how it was used over 2.5 years ago.

**Comment by ys** [comment] 2017-10-18 07:08
We are out of using hubot for this and I frankly don't remember the exactitude of that bug...

**Comment by aoberoi** [comment] 2018-03-29 23:44
seeing as how there's no trace of what this functionality actually was, i think the right thing to do is close this issue. feel free to comment if someone has more information to add, and we will re-open.

FYI: i looked inside the hipchat adapter and the only reference to `reply_to` i could find was this: https://github.com/hipchat/hubot-hipchat/blob/19199efee35815b32ed8a1c7f6156c80ddda36b9/src/hipchat.coffee#L27
so it seems that this is a property that is read when it exists, but not one that is depended on. sounds like something a legacy adapter might have popularized but no longer prefers.

**Closed by aoberoi** 2018-03-29 23:44 UTC
Labels: needs feedback
