### ISSUE TITLE
hubot does not reply to thread in catchAll

### ISSUE THREAD

**Issue by rophy** [slackapi/hubot-slack#428] opened 2017-08-03 09:58 UTC
* [V] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [V] I've read and agree to the [Code of Conduct](https://github.com/slackapi/hubot-slack/blob/master/CODE_OF_CONDUCT.md).
* [V] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

```
module.exports = function(robot) {
  robot.catchAll( function(res) {
    res.reply("Sorry, I don't understand");
  });
});
```

Expected: when hubot receives an unhandled command in a thread, hubot should respond to thread
Actual: when hubot receives an unhandled command in a thread, hubot responded to channel instead of thread.

#### Reproducible in:
hubot-slack version: 4.3.3
OS version(s): win7
Device(s): slack client

**Comment by aoberoi** [comment] 2017-08-21 23:39
thanks for the report. i haven't had time to try to reproduce this one yet, but i want you to know that we aren't ignoring your issue.

**Comment by aoberoi** [comment] 2017-12-18 02:53
@rophy as far as i can tell, the `res.catchAll()` method is supposed to respond in channel. if you prefer making a thread, i believe you use [this example](https://github.com/slackapi/hubot-slack/issues/451#issuecomment-350698583) to ensure the response is in a thread. closing since i think this should work, feel free to reply if it doesn't or if you have any more concerns.

**Closed by aoberoi** 2017-12-18 02:53 UTC

**Comment by wampa007** [comment] 2022-03-22 18:00
I ran into this same issue and had to create a workaround.  Seems that hear/respond listeners are passed a Response object based on msg.message, but CatchAll is passed the Message object directly (actually before being invoked I see: msg.message = msg.message.message, at https://github.com/hubotio/hubot/blob/7795fe53fb1a3dde85537589149cab0f0b58404a/src/robot.js#L232  ).  
The result is that to respond to 'msg' passed to catchAll does not respond to threads. I tried everything in CatchAll such as setting:
1) msg.message.thread_ts = msg.message.id
2) msg.thread_ts = msg.message.id
3) msg.thread_ts = msg.id

Nothing worked to respond back to the thread.
In fact, even where msg.message.thread_ts is already set because the message came from one, simply responding sends the message back to the channel, which does not happen when using hear/respond.

My workaround was to create my own Response object based on msg.message, then replace msg with the response object:
             const response = new robot.Response(robot, msg.message, true)
             msg = response

Looks like this is a bug in the original hubot file linked above.
